services:
  service_1:
    container_name: service_1
    build: ./service_1/
    expose:
      - "8001:8001"

  service_2:
    container_name: service_2
    build: ./service_2/
    expose:
      - "8002:8002"
  
  nginx:
    container_name: nginx
    build: ./nginx/
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - "service_1"
      - "service_2"
